### ISSUE TITLE
What is the license for kentUtils?

### ISSUE THREAD

**Issue by hartzell** [ENCODE-DCC/kentUtils#12]
The source code for [twoBitToFa](https://github.com/ENCODE-DCC/kentUtils/blob/master/src/utils/twoBitToFa/twoBitToFa.c) includes this comment about the license near the top:

```
/* Copyright (C) 2013 The Regents of the University of California 
 * See README in this or parent directory for licensing information. */
```

I can't find any local README.  At the top level there is [licenseUcscGenomeBrowser.txt](https://github.com/ENCODE-DCC/kentUtils/blob/master/licenseUcscGenomeBrowser.txt) which discusses the licensing requirements of the Genome Browser.

There are various other statements, such as the one in [slog.c](https://github.com/ENCODE-DCC/kentUtils/blob/d8376c5d52a161f2267346ed3dc94b5dce74c2f9/src/lib/slog.c)

```
 * This file is copyright 2002 Jim Kent, but license is hereby
 * granted for all use - public, private or commercial.  */
```

Is there a simple licensing statement that covers the contents of the repository?

**Comment by NullModel** [comment]
Please note the complete license information:

   http://genome.ucsc.edu/license/

**Comment by hartzell** [comment]
That's pretty much the same information that's in the `licenseUcscGenomeBrowser.txt`.

I'm not sure how to reconcile that with the various files in the tree that have statements like this from from slog.c (linked above):

> [...] license is hereby granted for all use - public, private or commercial. 

Which is it?  License required or license granted?

**Comment by NullModel** [comment]
As the license states, parts of the source tree are free to use.
Other parts require a license.  The src/lib/slog.c is in the free to use directory:

/* slog - fixed point scaled logarithm stuff.
  *
  * This file is copyright 2002 Jim Kent, but license is hereby
  * granted for all use - public, private or commercial. */

That says this file is free to use.

**Comment by hartzell** [comment]
Got it.  Thanks.
