### ISSUE TITLE
cannot compile mafToFa

### ISSUE THREAD

**Issue by vitalyg24** [ENCODE-DCC/kentUtils#18]
mafToFa is not provided. I've tried compile from the source by myself and got the errors below:

[vitalyg@cn100 mafToFa]$ make
gcc -O -g  -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -DUSE_SSL -DCOLOR32   -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -I../inc -I../../inc -I../../../inc -I../../../../inc -I../../../../../inc -I/include -I/usr/include/libpng15  -o mafToFa.o -c mafToFa.c
gcc -O -g -o /home/labs/training/vitalyg/bin/x86_64/mafToFa mafToFa.o ../../../lib/x86_64/jkweb.a -lm
../../../lib/x86_64/jkweb.a(linefile.o): In function `lineFileTabixMayOpen':
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:230: undefined reference to `ti_open'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:236: undefined reference to `ti_index_load'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:239: undefined reference to `ti_close'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:250: undefined reference to `ti_iter_first'
../../../lib/x86_64/jkweb.a(linefile.o): In function `lineFileSetTabixRegion':
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:267: undefined reference to `ti_get_tid'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:270: undefined reference to `ti_get_tid'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:273: undefined reference to `ti_queryi'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:277: undefined reference to `ti_iter_destroy'
../../../lib/x86_64/jkweb.a(linefile.o): In function `lineFileNext':
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:482: undefined reference to `ti_read'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:551: undefined reference to `bgzf_read'
../../../lib/x86_64/jkweb.a(linefile.o): In function `lineFileClose':
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:700: undefined reference to `ti_iter_destroy'
/home/labs/training/vitalyg/src/kentUtils/src/lib/linefile.c:701: undefined reference to `ti_close'
../../../lib/x86_64/jkweb.a(net.o): In function `sendFtpDataToPipeThread':
/home/labs/training/vitalyg/src/kentUtils/src/lib/net.c:925: undefined reference to `pthread_detach'
../../../lib/x86_64/jkweb.a(net.o): In function `netGetOpenFtpSockets':
/home/labs/training/vitalyg/src/kentUtils/src/lib/net.c:1054: undefined reference to `pthread_create'
../../../lib/x86_64/jkweb.a(https.o): In function `openssl_pthread_setup':
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:38: undefined reference to `CRYPTO_num_locks'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:42: undefined reference to `CRYPTO_set_id_callback'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:43: undefined reference to `CRYPTO_set_locking_callback'
../../../lib/x86_64/jkweb.a(https.o): In function `openSslInit':
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:74: undefined reference to `SSL_library_init'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:75: undefined reference to `ERR_load_crypto_strings'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:76: undefined reference to `ERR_load_SSL_strings'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:77: undefined reference to `OPENSSL_add_all_algorithms_noconf'
../../../lib/x86_64/jkweb.a(https.o): In function `netConnectHttpsThread':
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:92: undefined reference to `pthread_detach'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:104: undefined reference to `SSLv23_client_method'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:104: undefined reference to `SSL_CTX_new'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:129: undefined reference to `BIO_new_ssl_connect'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:131: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:143: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:145: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:149: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:153: undefined reference to `BIO_test_flags'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:157: undefined reference to `ERR_get_error'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:157: undefined reference to `ERR_reason_error_string'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:162: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:170: undefined reference to `BIO_test_flags'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:174: undefined reference to `BIO_test_flags'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:226: undefined reference to `BIO_ctrl'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:280: undefined reference to `BIO_write'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:283: undefined reference to `BIO_test_flags'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:285: undefined reference to `ERR_print_errors_fp'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:304: undefined reference to `BIO_read'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:308: undefined reference to `BIO_test_flags'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:316: undefined reference to `ERR_print_errors_fp'
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:342: undefined reference to `BIO_free_all'
../../../lib/x86_64/jkweb.a(https.o): In function `netConnectHttps':
/home/labs/training/vitalyg/src/kentUtils/src/lib/https.c:364: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make: *** [mafToFa] Error 1

**Comment by NullModel** [comment]
Good Evening Vitaly:

This is an ancient binary that hasn't been used in years.

Try changing the makefile to these three lines:

kentSrc = ../../..
A = mafToFa
include ${kentSrc}/inc/userApp.mk

And then 'make compile'

There is also a python script:
   https://github.com/maximilianh/maxtools/blob/master/maf2faFiles

--Hiram

**Comment by vitalyg24** [comment]
Hello Hiram,

A file has been compiled with no errors. Thank you for the quick response.

Vitaly.
