### ISSUE TITLE
faLowerToN compilation issue

### ISSUE THREAD

**Issue by aechchiki** [ENCODE-DCC/kentUtils#20]
As stated in the [manual](https://github.com/ucscGenomeBrowser/kent), to compile the specific utility in the `kent/src/utils/` folder, I followed points 1-7. 

It worked ok for most utilities that I needed, and the binaries execute correctly. 
I had exception for `faLowerToN`, for which I couldn't achieve the build:

```
aechchik@dee-serv04:/scratch/local/monthly/aechchik/kent/src/utils/faLowerToN$ make
gcc -O -g -o /home/aechchik/bin/x86_64/faLowerToN faLowerToN.o ../../lib/x86_64/jkweb.a -lpthread -L/lib -lssl -lcrypto ../../htslib/libhts.a -L/software/lib64 -lpng16 -lz -lm -lm
../../lib/x86_64/jkweb.a(dnautil.o): In function `lowerToN':
/scratch/local/monthly/aechchik/kent/src/lib/dnautil.c:694: multiple definition of `lowerToN'
faLowerToN.o:/scratch/local/monthly/aechchik/kent/src/utils/faLowerToN/faLowerToN.c:29: first defined here
collect2: error: ld returned 1 exit status
make: *** [faLowerToN] Error 1
```

Anyone knows how I could fix this?

Best,
Amina

**Comment by NullModel** [comment]
Good Morning Amina:

The faLowerToN is an obsolete program that does not build correctly
at this time.

In place of that you can use the command: maskOutFa
and a binary of that command can be found at:

    http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/maskOutFa
    http://hgdownload.soe.ucsc.edu/admin/exe/macOSX.x86_64/maskOutFa

Used with these arguments:

    maskOutFa input.fa hard output.fa

See also:  http://hgdownload.soe.ucsc.edu/downloads.html#source_downloads
which is the updated replacement source for the EncodeDCC kentUtils

--Hiram

**Comment by aechchiki** [comment]
Thanks for the feedback @NullModel. 
I'll take note of that. 

I actually needed this binary to execute scripts in the [Haplomerger2](https://github.com/mapleforest/HaploMerger2) suite, at least according to the pre-compiled binaries delivered in their package. I think I'll have to contact the authors to see what changes I should apply to make it work in my environment. I tried a quick lookup in their code and dependencies to look for this binary (`grep -rnw . -e 'faLowerToN'`) and there was no output. So it's clearly called somewhere internally. I hope I will eventually manage. Unless you have any experience from this side?

Meanwhile, thanks for your answer. 
Amina

**Comment by NullModel** [comment]
You can fix this source code by changing the name of
the subroutine in faLowerToN.c, add an X to the name
on two different lines:

void XlowerToN(char *s)

      XlowerToN(line);

I note the HaploMerger2 package you mention actually includes
all of the programs as binaries.  The faLowerToN is included
in their release package.  You shouldn't need to be building anything
at all, they claim their release has everything required.
Well, for centos and two versions of ubuntu.

However, if you really want kent programs, you should use the
official UCSC distribution.  The Encode DCC copy is obsolete.

**Comment by aechchiki** [comment]
Thanks!

Unfortunately I have to use CentOS7  so I have to recompile (their binaries didn't work on my distribution). I'll use kent programs from the official UCSC distribution as you suggest.

**Comment by NullModel** [comment]
You will still have to modify the source as I mentioned to get even
the UCSC distribution to compile.  That is a program we no longer build
in the standard procedures.

**Comment by aechchiki** [comment]
I downloaded the version you suggest, and modified then script as follows(couldn't find the exact lines you were referring to). I still get: 

```
aechchik@dee-serv04:/scratch/local/monthly/aechchik/test/userApps/kent/src/utils/faLowerToN$ make
gcc -O -g -o /home/aechchik/bin/x86_64/faLowerToN faLowerToN.o ../../lib/x86_64/jkweb.a -lpthread -L/lib -lssl -lcrypto ../../htslib/libhts.a -L/software/lib64 -lpng16 -lz -lm -lm
../../lib/x86_64/jkweb.a(dnautil.o): In function `lowerToN':
/scratch/local/monthly/aechchik/test/userApps/kent/src/lib/dnautil.c:694: multiple definition of `lowerToN'
faLowerToN.o:/scratch/local/monthly/aechchik/test/userApps/kent/src/utils/faLowerToN/faLowerToN.c:29: first defined here
collect2: error: ld returned 1 exit status
make: *** [faLowerToN] Error 1
```

Here is my source:
```
aechchik@dee-serv04:/scratch/local/monthly/aechchik/test/userApps/kent/src/utils/faLowerToN$ cat faLowerToN.c
/* faLowerToN - Convert lower case bases to N.. */

/* Copyright (C) 2011 The Regents of the University of California
 * See README in this or parent directory for licensing information. */
#include "common.h"
#include "linefile.h"
#include "hash.h"
#include "options.h"


void usage()
/* Explain usage and exit. */
{
errAbort(
  "faLowerToN - Convert lower case bases to N.\n"
  "usage:\n"
  "   faLowerToN input.fa output.fa\n"
  "options:\n"
  "   -xxx=XXX\n"
  );
}

static struct optionSpec options[] = {
   {NULL, 0},
};

void lowerToN(char *s)
/* Convert lower case letters to N's. */
{
char c;
for (;;)
    {
    c = *s;
    if (islower(c))
        *s = 'N';
    else if (c == 0)
        break;
    ++s;
    }
}

void XLowerToN(char *inName, char *outName)
/* faLowerToN - Convert lower case bases to N.. */
{
struct lineFile *lf = lineFileOpen(inName, TRUE);
FILE *f = mustOpen(outName, "w");
char *line;
while (lineFileNext(lf, &line, NULL))
    {
    if (line[0] != '>')
       lowerToN(line);
    fprintf(f, "%s\n", line);
    }
carefulClose(&f);
}

int main(int argc, char *argv[])
/* Process command line. */
{
optionInit(&argc, argv, options);
if (argc != 3)
    usage();
XLowerToN(argv[1], argv[2]);
return 0;
}

```

Shall I also modify something elsewhere?
Thanks

**Comment by JimKent** [comment]
Hmm, try deleting the .o file and rerunning the make.  Somehow it is not
recompiling before relinking, but it needs to.  It may be that the
timestamps on the files are a bit off.  At any rate deleting faLowerToN.o
should force a recompile.

Take care,
     Jim

**Comment by aechchiki** [comment]
wow! touching files to uniform timestamps & deleting faLowerToN.o worked. 
many many thanks!
Amina

**Comment by NullModel** [comment]
I'm curious Amina, what did you exactly do ?
The previous alteration you mentioned to the source
code would not have solved the problem and it had
nothing to do with objects or timestamps.  I'm confused.

The source code has been fixed in the UCSC git repository.
If you have up to date top of tree git source, it would
work without modification.

--Hiram

**Comment by aechchiki** [comment]
Sure. 

So, following your instructions:
- downloaded the most recent version from USCS: `wget http://hgdownload.soe.ucsc.edu/admin/exe/userApps.v362.src.tgz`
- unpacked `tar -xvzf userApps.v362.src.tgz`
- built:`cd /kent/src/lib; make` ; `cd kent/src/htslib; make` ; `cd kent/src/jkOwnLib; make`
- tried: `cd /kent/src/utils/; make` but failed again with `collect2: error: ld returned 1 exit status`
- modified the code as you suggested (`faLowerToN -> XLowerToN`), tried again: `cd /kent/src/utils/; make`, always same error
- went back to the `/kent` root and executed `find . -exec touch {} \;`
- tried again: `cd /kent/src/utils/; make` -> always same error
- fixed code adding `static` to the `LowerToN` function. now it works

But I can simply try your fix from the USCS github, not sure what you did there (didn't check) but if you say that it works with no further tricks, then it is even better.

Thanks !

**Comment by aechchiki** [comment]
Ok wait. Turns out I could "just" added the static to the `LowerToN` function. And this is exactly what you did in the repo (last commit), if I am not wrong! Well, probably no need for the `XLowerToN`, I could just left it as `faLowerToN` (as you did).

It took me a while, had to google a lot. 
Excuse my non-existing knowledge of C.
