### ISSUE TITLE
wigToBigWig "X Y doesn't intersect X  X"

### ISSUE THREAD

**Issue by PanosFirmpas** [ENCODE-DCC/kentUtils#7]
Hello,

I was trying to convert a home-made bedgraph to a bigwig with wigToBigWig and I just can't
figure out what the problem is:

My first few lines look like this:
```
chr12	17	22	0.0333333333333333
chr12	23	25	0.0333333333333333
chr12	29	35	0.0333333333333333
```

Then I call : 
wigToBigWig my.bg chrominfo.txt test.bw

and I get this:
17 22 doesn't intersect 17 17, chromId 0 chromSize 49229541
Internal error bbiWrite.c 413

If I change the top line to 17 17
```
chr12	17	17	0.0333333333333333
chr12	23	25	0.0333333333333333
chr12	29	35	0.0333333333333333
```

it complains about the second one:
23 25 doesn't intersect 23 23, chromId 0 chromSize 49229541
Internal error bbiWrite.c 413

Interestingly, if I plug in a line copied from another bg like this:
```
chr1	2212490	2213641	22.4666666666667
chr12	17	17	0.0333333333333333
chr12	23	25	0.0333333333333333
chr12	29	35	0.0333333333333333
chr12	48	54	0.0333333333333333
chr12	101	101	0.0333333333333333
chr12	102	107	0.0333333333333333
```

some more  good lines?:
```
chr1	2212490	2213641	22.4666666666667
chr1	2213646	2214316	22.4666666666667
chr1	2214321	2214988	22.4666666666667
chr1	2214993	2216216	22.4666666666667
chr1	2216221	2216323	22.4666666666667
chr1	2216328	2216647	22.4666666666667
chr1	2216652	2216828	22.4666666666667
chr1	2216833	2217099	22.4666666666667
```
Works fine

This? :
```
chr1	48	55	0.0333333333333333
chr1	101	101	0.0333333333333333
chr1	2214321	2214988	22.4666666666667
chr1	2214993	2216216	22.4666666666667
chr1	2216221	2216323	22.4666666666667
chr1	2216328	2216647	22.4666666666667
```
**48 55 doesn't intersect 48 48, chromId 0 chromSize 58871917**

Remove the **second** line !?!?!?!?!:
```
chr1	48	55	0.0333333333333333
chr1	2214321	2214988	22.4666666666667
chr1	2214993	2216216	22.4666666666667
chr1	2216221	2216323	22.4666666666667
chr1	2216328	2216647	22.4666666666667
```
**works like a charm**

What does it want from me?

**Comment by NullModel** [comment]
Good Morning:

It appears your chrominfo.txt file may be incorrect.
It should be two columns:
chromName   sizeOfChrom

And the chromName column 1 names should match the chrom names
you have you your wiggle text file.

Is there something unusual in chrominfo.txt ?

--Hiram

**Comment by PanosFirmpas** [comment]
Good Morning!

Thank you for the prompt reply!

My chrominfo had 3 columns, I kept the first two, and the top few chromosomes so now my chrominfo is exactly this:

```
chr4    76625712
chr7    74082188
chr5    71715914
chr3    62385949
chr6    60272633
chr2    59543403
chr15   58871917
chr9    56892771
chr16   55381981
chr20   55370968
```

And with a testbg of:
```
chr15   17      22      1.
chr15   29      35      1.
chr15   48      54      1
chr15   101     101     2
chr15   102     107     3
chr15   108     108     1
chr15   116     122     1
chr15   128     134     1
chr15   138     144     2
chr15   160     166     2
```

I get, again,
```
wigToBigWig testsmall.bg chrominfo_test.txt test.bw
17 22 doesn't intersect 17 17, chromId 0 chromSize 58871917
Internal error bbiWrite.c 413
```

**Comment by NullModel** [comment]
I have this reproduced here.  Will see what it means.

I do note the bedGraphToBigWig is successful, the wigToBigWig
should be able to process it, but it fails.

**Comment by NullModel** [comment]
Your bedGraph input data has zero-width items:
chr15   101     101     2
chr15   108     108     1

We can not process such items.  The error output could
be more clear.

**Comment by PanosFirmpas** [comment]
I see, that makes sense, thanks !
