### ISSUE TITLE
gtfToGenePred: "doesn't appear to be a GTF file (GFF not supported by this program)"

### ISSUE THREAD

**Issue by remimarenco** [ENCODE-DCC/kentUtils#8]
Hi!

First, thanks for your awesome tool suite, it is really helpful everyday in my job.

Second, the less nice part...I have an issue with gtfToGenePred :/.

When I am running the tool against a (supposed) GTF file, gtfToGenePred outputs me that it `doesn't appear to be a GTF file (GFF not supported by this program)`.

[myGtf_original.gtf.txt](https://github.com/ENCODE-DCC/kentUtils/files/254200/myGtf_original.gtf.txt)

I have tried to look into the GTF specification format, in case the tool I am using (Augustus) does not output a real GTF, and maybe it appears the second column with the name of the tool, is not in the specification.

So I removed it (as attached), and so the tool outputs me `col 3 or 4 not a number  Bad line 3 of myGtf.gtf`.

[myGtf_without_2nd_column.tabular.txt](https://github.com/ENCODE-DCC/kentUtils/files/254201/myGtf_without_2nd_column.tabular.txt)

So I thought maybe it was because of the comments, so I cleaned everything (as attached), and I got back the message that it is not a GTF File :(.

[myGtf_without_comments.gtf.txt](https://github.com/ENCODE-DCC/kentUtils/files/254202/myGtf_without_comments.gtf.txt)

Do you have any idea about what is going on?

Thanks a lot!

**Comment by remimarenco** [comment]
I just also tried with a GFF2 (in the [ensembl website](http://useast.ensembl.org/info/website/upload/gff.html) they describe it), as it seems it is the same thing than GTF, but I got the same :(.
[5.gff.txt](https://github.com/ENCODE-DCC/kentUtils/files/254206/5.gff.txt)

**Comment by NullModel** [comment]
The sequence of processing augustus output into genePred is as follows:

<pre>
find ./run.augustus/gtf -type f | grep ".gtf.gz$" \
   | sed -e 's#/# _D_ #g; s#\.# _dot_ #g;' \
     | sort -k11,11 -k13,13n \
      | sed -e 's# _dot_ #.#g; s# _D_ #/#g' | xargs zcat \
        | /hive/data/outside/augustus/augustus.3.1/scripts/join_aug_pred.pl \
           | grep -P "\t(CDS|exon|stop_codon|start_codon|tts|tss)\t" \
             > $db.augustus.gtf
gtfToGenePred -genePredExt -infoOut=$db.info $db.augustus.gtf $db.augustus.gp
</pre>

**Comment by remimarenco** [comment]
Great! Thanks a lot for taking the time :)

**Comment by parthingle** [comment]
Hi!

I'm having the same problem, but slightly different. I used gffread (https://github.com/gpertea/gffread) to first convert my .gff file to .gtf, then used gtfToGenePred on it, but I'm getting the same error

my gtf file created from gffread is here: https://www.dropbox.com/s/i1lh25okfvwprgi/taeGut2_gff.gtf?dl=0

Can you see where I'm going wrong?

Thank you!
